import * as d3 from "d3";
import { SamplingAnalysisData, Vocabulary } from "./data";
export declare const CONFIG: {
    margin: {
        top: number;
        right: number;
        bottom: number;
        left: number;
    };
    cellHeight: number;
    cellWidth: number;
    sampledCharFontSize: string;
    cellTokenFontSize: string;
    heatmapPadding: number;
    highlightBackgroundColor: string;
    highlightStrokeColor: string;
    highlightStrokeWidth: number;
    axisTextColor: string;
    pillBgColor: string;
    pillPaddingX: number;
    pillPaddingY: number;
    pillBorderRadius: number;
    hoverHighlightColor: string;
    infoTextColor: string;
    infoTextFontSize: string;
    colorInterpolator: typeof d3.interpolateBrBG;
    probColorInterpolator: typeof d3.interpolateBrBG;
    tooltipBgColor: string;
    tooltipTextColor: string;
    tooltipPadding: string;
    tooltipBorderRadius: string;
    tooltipFontSize: string;
    dynamicTextColorThreshold: number;
    lightTextColor: string;
    darkTextColor: string;
    probPlotHeight: number;
    probPlotTopN: number;
    probPlotAxisColor: string;
    probPlotLabelFontSize: string;
};
export declare const render: (containerSelector: string, data: SamplingAnalysisData, vocab: Vocabulary, userConfig?: any) => void;
export declare function initSamplingWithControls(containerSelector: string, sampleDataSets: SamplingAnalysisData[], vocab: Vocabulary): void;
