export declare class QuantizationVisualization {
    private svgMainContainer;
    private errorBarsSvg;
    private slidersContainer;
    private svgWrapper;
    private currentSourceMatrix;
    private currentQuantType;
    private currentConfig;
    private tooltip;
    private activeInputElement;
    private readonly blockBaseColors;
    private readonly cellSize;
    private readonly margin;
    constructor();
    initialize(): void;
    private setupDOM;
    private createCallout;
    private createControls;
    private createControlsContainer;
    private createParameterSliders;
    private createSVGWrapper;
    private setupSVG;
    private redrawVisualization;
    private drawMatrices;
    private drawMatrixTitles;
    private drawSourceMatrix;
    private drawQuantizedMatrix;
    private drawDequantizedMatrix;
    private drawNumberLines;
    private drawBlockNumberLine;
    private drawErrorBars;
    private createColorScales;
    private showQuantizationTooltip;
    private showDequantizationTooltip;
    private showTooltip;
    private hideTooltip;
    private createTooltip;
    private handleSourceCellClick;
    private showEditableInput;
    private removeActiveInputElement;
}
export declare function quantTypeInteractive(): void;
